**Numpy NumPy is one of the most important libraries and is often used in the Python programming language for numerical computing**

**NumPy arrays are the basic data structures used in NumPy (Numeric Python) libraries.**

In [4]:
import numpy as np

In [5]:
print(np.__version__)

1.24.3


In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(type(arr))

<class 'numpy.ndarray'>


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [12]:
# Task 1

import numpy as np

# Create NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Calculating average
rata_rata = np.mean(arr)
print("Rata-rata:", rata_rata)

# Counts the number of elements
jumlah = np.sum(arr)
print("Jumlah:", jumlah)

# Searching for maximum and minimum values
nilai_max = np.max(arr)
nilai_min = np.min(arr)
print("Nilai maksimum:", nilai_max)
print("Nilai minimum:", nilai_min)



Rata-rata: 3.0
Jumlah: 15
Nilai maksimum: 5
Nilai minimum: 1


In [ ]:
# Task 1

In [16]:
import numpy as np

In [17]:
print(np.__version__)

1.24.3


In [14]:
import numpy as np

# Create array with zero range up to ten
arr = np.arange(11)

# Show array
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
# Use type() function to check data types
import numpy as np

arr = np.arange(11)

print(type(arr))  


<class 'numpy.ndarray'>


In [21]:
import numpy as np

# Create a 2x4 matrix
matriks = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing matrix elements
elemen_1_2 = matriks[0, 1]  # First row, second column
elemen_2_3 = matriks[1, 2]  # Second row, third column

print("Elemen pada baris 1, kolom 2:", elemen_1_2)
print("Elemen pada baris 2, kolom 3:", elemen_2_3)


Elemen pada baris 1, kolom 2: 2
Elemen pada baris 2, kolom 3: 6


In [ ]:
# Numpy Advanced

In [22]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [24]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np

# Create a 2x3 matrix
matriks = np.array([[1, 2, 3], [4, 5, 6]])

# Display matrix in string format
for baris in matriks:
    for elemen in baris:
        print(f"{elemen:2d}", end=" ")
    print()


 1  2  3 
 4  5  6 


In [ ]:
# Task 2

In [26]:
# Creating 0-D array (scalar)
import numpy as np
skalar = np.array(52)
print("0-D Array (Skalar):")
print(skalar)


0-D Array (Skalar):
52


In [27]:
# Create 1-D array (vector)
import numpy as np
vektor = np.array([1, 2, 3, 4, 5])
print("1-D Array (Vektor):")
print(vektor)


1-D Array (Vektor):
[1 2 3 4 5]


In [24]:
# Create 2-D array (Matrix)
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print("Dimensi:", matrix.ndim)


[[1 2 3]
 [4 5 6]]
Dimensi: 2


In [5]:
# Create a three-dimensional array
import numpy as np

data = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(data)
print("Dimensi:", data.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensi: 3


In [35]:
# Task 3 create arrays of various dimensions
array_0d = np.array(52)  
array_1d = np.array([1, 2, 3])  
array_2d = np.array([[4, 5], [6, 7]])  
array_3d = np.array([[[8, 9], [10, 11]], [[12, 13], [14, 15]]])  

# Merging all arrays into one large array
gabung = np.hstack((np.atleast_1d(array_0d), array_1d, array_2d.reshape(-1), array_3d.reshape(-1)))

# Show merge results
print("Hasil Penggabungan:")
print(gabung)

# Checking each array's dimensions
print("\nDimensi Array:")
print("0-D Array (Skalar):", array_0d.ndim)
print("1-D Array (Vektor):", array_1d.ndim)
print("2-D Array (Matriks):", array_2d.ndim)
print("3-D Array:", array_3d.ndim)


Hasil Penggabungan:
[52  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Dimensi Array:
0-D Array (Skalar): 0
1-D Array (Vektor): 1
2-D Array (Matriks): 2
3-D Array: 3


In [ ]:
# Advanced

In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


In [41]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Accessing elements in row 1, column 2
print('Elemen pada baris 1, kolom 2:', arr[0, 1])


Elemen pada baris 1, kolom 2: 2


In [44]:
# Task 4

import numpy as np

#  2D array with 3 lists (lines)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9,]])

# Using add operations operation
jumlah = np.sum(array_2d)
print("Hasil Penjumlahan Semua Elemen:")
print(jumlah)

# Slicing to access specific rows and columns
baris_ke_2 = array_2d[1]  # second line (index 1)
kolom_ke_2 = array_2d[:, 1]  # second column (index 1)

print("\nElemen Baris Kedua:")
print(baris_ke_2)

print("\nElemen Kolom Kedua:")
print(kolom_ke_2)


Hasil Penjumlahan Semua Elemen:
45

Elemen Baris Kedua:
[4 5 6]

Elemen Kolom Kedua:
[2 5 8]


In [47]:
# Advanced
import numpy as np

array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  

elemen = array[1, 0, 2]

print("Elemen di indeks (1, 0, 2):", elemen)

Elemen di indeks (1, 0, 2): 9


In [49]:
import numpy as np

array = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]])  

elemen = array[0, 1, -1]

print("Elemen terakhir dalam matriks indeks (0, 1):", elemen)


Elemen terakhir dalam matriks indeks (0, 1): 10


In [1]:
import numpy as np

# Create numpy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Access elements by index
elemen_pertama = arr[0]  # Accessing the first element with index 0
elemen_kelima = arr[4]   # Accessing fifth element with index 4
elemen_terakhir = arr[-1] # Accessing last element with index -1

print("Elemen pertama:", elemen_pertama)
print("Elemen kelima:", elemen_kelima)
print("Elemen terakhir:", elemen_terakhir)


Elemen pertama: 1
Elemen kelima: 5
Elemen terakhir: 10
