_Pandas is a Python library licensed by BSD and open source that provides easy-to-use data structures and data analysis_

In [117]:
import pandas as pd
import numpy as np

In [118]:
data = pd.Series([0.25, 0.50, 0.75, 1], index=['a', 'b', 'c', 'd'])

In [123]:
# Change in series
data = pd.Series(data)

In [124]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [121]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [122]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [103]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [105]:
data[2]

0.75

_Implicit index in Pandas context refers to the default index that is automatically given to rows or columns in DataFrame or Series if you do not manually provide an explicit index (index name)_

_This explicit index makes it easier to refer to a particular row or column in the DataFrame or Series based on a predefined label_

In [104]:
# Explicit Index: This is the index that you explicitly set when you create a DataFrame or Series.
data['a']

0.25

In [ ]:
# Task 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_list = [10, 20, 30, 40, 50]

In [3]:
print(data_list)

[10, 20, 30, 40, 50]


In [5]:
data_series = pd.Series(data_list)

In [6]:
print(data_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [29]:
# Index Data

In [30]:
data.index

RangeIndex(start=0, stop=7, step=1)

In [31]:
# Create a list with a range of 1-10
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
data[2]

30

In [ ]:
# Task 2

In [20]:
import pandas as pd
import numpy as np

In [21]:
# Create Series with explicit indexes
data = [10, 20, 30, 40, 50, 'MyEduSolve', 8.09]

In [22]:
print(data)

[10, 20, 30, 40, 50, 'MyEduSolve', 8.09]


In [23]:
data = pd.Series(data)

In [24]:
data

0            10
1            20
2            30
3            40
4            50
5    MyEduSolve
6          8.09
dtype: object

In [25]:
# "Values" refers to the portion of data that contains actual values in the DataFrame or Series.
data.values

array([10, 20, 30, 40, 50, 'MyEduSolve', 8.09], dtype=object)

In [26]:
# "Index" refers to the component used to identify each row or entity in the DataFrame or Series.
data.index

RangeIndex(start=0, stop=7, step=1)

In [27]:
data[0:5]

0    10
1    20
2    30
3    40
4    50
dtype: object

In [28]:
# This Implicit Index is an integer that starts at zero and continues to increase for each line or element.
data[3:9]

3            40
4            50
5    MyEduSolve
6          8.09
dtype: object

In [ ]:
# Task 3

In [46]:
import pandas as pd
import numpy as np

In [48]:
absen = pd.Series([1, 3, 5, 6], index=['Daniel','Fitri', 'Aulia', 'Salsa'])

In [49]:
absen

Daniel    1
Fitri     3
Aulia     5
Salsa     6
dtype: int64

In [50]:
absen.values

array([1, 3, 5, 6], dtype=int64)

In [51]:
absen.index

Index(['Daniel', 'Fitri', 'Aulia', 'Salsa'], dtype='object')

In [52]:
absen['Daniel']

1

In [ ]:
# Advanced

In [53]:
data_2 = pd.Series([0.25, 0.50, 0.75, 1], index=[2, 5, 3, 7])

In [54]:
data_2[2]

0.25

In [55]:
data = pd.Series([0.25, 0.50, 0.75, 1], index=['a', 'b', 'c', 'd'])

In [56]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [57]:
data['b': 'c']

b    0.50
c    0.75
dtype: float64

In [58]:
data['1':'2']

Series([], dtype: float64)

In [ ]:
# Task 4

In [69]:
D = pd.Series([1, 2, 3, 4, 5, 'Data_Analyst', 12, 15, 17],
                        index=[20, 30, 40, 50, 60, 70, 80, 90, 100])

In [70]:
D

20                1
30                2
40                3
50                4
60                5
70     Data_Analyst
80               12
90               15
100              17
dtype: object

In [74]:
D[50]

4

In [75]:
D[0]

KeyError: 0

In [ ]:
# Task 5

In [76]:
import pandas as pd

In [78]:
data = pd.Series([10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
                        index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'])

In [79]:
data

A     10
B     20
C     30
D     40
E     50
F     60
G     70
H     80
I     90
J    100
dtype: int64

In [80]:
data['A':'B']

A    10
B    20
dtype: int64

In [82]:
data[1:6:2] # 3 implicit parameters

B    20
D    40
F    60
dtype: int64

In [84]:
data[3:6:8] # 3 Parameters

D    40
dtype: int64

In [86]:
data[7:9] # parameters

H    80
I    90
dtype: int64